server:
  port: 7080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7080/eureka
    register-with-eureka: false
    fetch-registry: false
spring:
  application:
    name: wexin-eureka
